@extends('include.admindashboard')

@section('body')
<div class="page-content"><div class="container"><div class="card content-area"><div class="card-innr"><div class="card-head"><h4 class="card-title">Received  {{$coin->name}}</h4></div><table class="data-table dt-init user-tnx"><thead><tr class="data-item data-head"><th class="data-col dt-tnxno">Tranx NO</th><th class="data-col dt-token">Amount</th><th class="data-col dt-amount">Confirmations</th> <th class="data-col dt-account">Time</th><th class="data-col dt-type"><div class="dt-type-text">Status</div></th><th class="data-col"></th></tr></thead><tbody>


@foreach($trx['data']['txs'] as $trx)

<!-- .data-item --><tr class="data-item"><td class="data-col dt-tnxno"><div class="d-flex align-items-center"><div class="data-state data-state-approved"><span class="d-none">Approved</span></div><div class="fake-class"><span class="lead tnx-id">{{substr($trx['txid'], 0, 8)}}...</span><span class="sub sub-date"><? echo date("D,d-M.Y", $trx['time']) ?> <? echo date("h:i:s A", $trx['time'])?></span></div></div></td><td class="data-col dt-token"><span class="lead token-amount"><? echo $trx['amounts_received'][0]['amount'];?>  </span><span class="sub sub-symbol">{{$coin->currency}}</span></td><td class="data-col dt-amount"><span class="lead amount-pay">{{$trx['confirmations']}}</span><span class="sub sub-symbol">Confs. <em class="fas fa-info-circle" data-toggle="tooltip" data-placement="bottom" title="Total Network Confirmations"></em></span></td> <td class="data-col dt-account"><span class="lead user-info">{{$trx['time']}}</span><span class="sub sub-date">{{date("d/m/Y h:i:s A", $trx['time'])}}</span></td><td class="data-col dt-type"><span class="dt-type-md badge badge-outline badge-success badge-md">Received</span><span class="dt-type-sm badge badge-sq badge-outline badge-success badge-md">P</span></td><td class="data-col text-right"><a href="#" data-toggle="modal" data-target="#transaction{{$trx['time']}}details" class="btn btn-light-alt btn-xs btn-icon"><em class="ti ti-eye"></em></a></td></tr><!-- .data-item -->




<!-- Modal Large --><div class="modal fade" id="transaction{{$trx['time']}}details" tabindex="-1"><div class="modal-dialog modal-dialog-lg modal-dialog-centered"><div class="modal-content"><a href="#" class="modal-close" data-dismiss="modal" aria-label="Close"><em class="ti ti-close"></em></a><div class="popup-body popup-body-lg"><div class="content-area"><div class="card-head d-flex justify-content-between align-items-center"><h4 class="card-title mb-0">Transaction Details</h4></div><div class="gaps-1-5x"></div><div class="data-details d-md-flex"><div class="fake-class"><span class="data-details-title">Tranx Date</span><span class="data-details-info"><? echo date("D,d-M.Y", $trx['time']) ?> </span></div><div class="fake-class"><span class="data-details-title">Tranx Status</span><span class="badge badge-success ucap">Successful</span></div><div class="fake-class"><span class="data-details-title">Tranx Approved Time</span><span class="data-details-info">  {{date("d/m/Y h:i:s A", $trx['time'])}}</span></div></div><div class="gaps-3x"></div><h6 class="card-sub-title">Transaction Info</h6><ul class="data-details-list"><li><div class="data-details-head">Transaction Type</div><div class="data-details-des"><strong>Received</strong></div></li><!-- li --><li><div class="data-details-head">Amount</div><div class="data-details-des"><strong>{{$trx['amounts_received'][0]['amount']}} <small> {{$coin->currency}}</small></strong></div></li><!-- li --><li><div class="data-details-head">Sent From</div><div class="data-details-des"><strong>{{$trx['senders'][0]}}</strong></div></li><!-- li --><li><div class="data-details-head">TRX Number</div><div class="data-details-des"><span>{{$trx['txid']}}</span> <span></span></div></li><!-- li --><li><div class="data-details-head">Wallet</div><div class="data-details-des"><span>{{$trx['amounts_received'][0]['recipient']}}</span> <span></span></div></li><!-- li --><li><div class="data-details-head">Confirmations</div><div class="data-details-des">{{$trx['confirmations']}}</div></li><!-- li --></ul> </div><!-- .card --></div></div><!-- .modal-content --></div><!-- .modal-dialog --></div><!-- Modal End -->
@endforeach




<!-- .data-item --></tbody></table></div><!-- .card-innr --></div><!-- .card --></div><!-- .container --></div>
@endsection
